version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image_name: chethankumar6/mysql
    container_name: mysql
    volume:
    - mysql: /var/lib/mysql
  backend:
    image_name: chethankumar6/backend
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image_name: chethankumar6/frontend
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend